version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install pip name
          command: python -m ensurepip --upgrade
      - run:
          name: install requirements hahahah
          command: |
            ls

  setup_db:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            ls

  run_project:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            ls

  unit_tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            cd IDSIT
            pip install -r requirements.txt
            cd vuln/Tests/unit_tests/
            python unit1.py

  integration_tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Start Django Development Server in Background
          command: |
            cd IDSIT
            pip install -r requirements.txt
            python manage.py runserver 127.0.0.1:8000 &
            sleep 5
      - run:
          name: Run Integration Tests
          command: |
            cd IDSIT/vuln/Tests/integration_tests/
            python int.py
            python int2.py

  quality_test:
    resource_class: "windows.medium"
    machine:
      image: "windows-server-2022-gui:current"
      shell: "powershell.exe -ExecutionPolicy Bypass"
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            cd IDSIT/vuln/Tests/quality_test/
            pip install flake8
            flake8 ../../.. > /IDSIT/vuln/Tests/quality_test/quality.txt
            dir

  report:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            cd IDSIT/vuln/Tests/
            python report.py
  MyJob1:
    resource_class: "windows.medium"
    machine:
      image: "windows-server-2022-gui:current"
      shell: "powershell.exe -ExecutionPolicy Bypass"
    steps:
      - checkout
      - run:
          name: here is a name IDSIT
          command: |
            ls
            echo "my name is imad" > name.txt
            cat name.txt
  MyJob2:
    machine:
      image: windows-default
    steps:
      - checkout
      - run:
          name: here is a seconf name devops
          command: |
            ls
            java --version
            python --vserion

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - MyJob1:
          requires:
            - build
      - MyJob2:
          requires:
            - build
      - setup_db:
          requires:
            - MyJob1
            - MyJob2
      - run_project:
          requires:
            - setup_db
      - unit_tests:
          requires:
            - run_project
      - integration_tests:
          requires:
            - run_project
      - quality_test:
          requires:
            - run_project
      - report:
          requires:
            - unit_tests
            - integration_tests
            - quality_test
