# Generated by Django 4.2.2 on 2024-09-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
